### PR TITLE
Issue#10: Improved UI of cards (fixed)

### PR DESCRIPTION
**Pull request by ishitaraina1807**
Changed "best place" to "Provider" 
And removed the alert message.

### CODE REVIEW

**Comment by RishabhJain0721** [comment]
Screenshot_2023-10-22-23-51-23-67_40deb401b9ffe8e1df2f1cc5ba480b12

User profile section on desktop view🥲

**Comment by ishitaraina1807** [comment]
It's cant beee!! okaay lemme fix it too

**Comment by ishitaraina1807** [comment]
Hey! For me, there's nothing in the user profile 
image
Can yo help me with this? 
I can make an item for myself, I tried but was not able to submit the details.

**Comment by RishabhJain0721** [comment]
Hi @ishitaraina1807 
Sorry for responding late. Was at a family function.
To add an item you can use the sell option on the dashboard navbar. A form will open where you can add details of item and submit.

**Comment by ishitaraina1807** [comment]
> Hi @ishitaraina1807 Sorry for responding late. Was at a family function. To add an item you can use the sell option on the dashboard navbar. A form will open where you can add details of item and submit.

I did that, but when i am clicking on submit, nothing is happening. 
Tried in live website as well as the local host too.

**Comment by RishabhJain0721** [comment]
@ishitaraina1807 
Please check if the images you are uploading are under the allowed size(500 KB) and then upload.

**Comment by ishitaraina1807** [comment]
@RishabhJain0721 ahh right, i wasnt checking that but...
there is some issue with the site now. 
I cloned the repo and here is the error:
image

Check the live website

**Comment by RishabhJain0721** [comment]
@ishitaraina1807 just checked the live site. Found no issues while adding an item. Dunno what's happening on your side :(

**Comment by ishitaraina1807** [comment]
Ahh just fixed everything
lemme create a new PR

**Pull request closed without merging**
