### PR TITLE
footer_at_bottom

### PR DESCRIPTION
**Pull request by Eklavya-sus**
#14 solved

### CODE REVIEW

**Comment by RishabhJain0721** [comment]
Screenshot_2023-10-22-17-39-30-05_40deb401b9ffe8e1df2f1cc5ba480b12


The positioning of orange line is displaced somehow.
Please look into that.

**Comment by Eklavya-sus** [comment]
Ah i will fix that right away

**Comment by Eklavya-sus** [comment]
Screenshot 2023-10-22 at 10 09 14 PM
Screenshot 2023-10-22 at 10 10 11 PM
Screenshot 2023-10-22 at 10 10 18 PM

**Comment by Eklavya-sus** [comment]
fixed

**Comment by RishabhJain0721** [comment]
Thanks @Eklavya-sus

**Comment by RishabhJain0721** [comment]
Hi @Eklavya-sus 
It would be great if you could give this repo a star.

**Comment by Eklavya-sus** [comment]
Sure. Thanks for merging my pr

**Pull request merged**
